In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [9]:
# load dataset
df = pd.read_csv('raw_sales.csv')

In [10]:
df.head(5)

datesold  postcode   price propertyType  bedrooms
0  2007-02-07 00:00:00      2607  525000        house         4
1  2007-02-27 00:00:00      2906  290000        house         3
2  2007-03-07 00:00:00      2905  328000        house         3
3  2007-03-09 00:00:00      2905  380000        house         4
4  2007-03-21 00:00:00      2906  310000        house         3

In [11]:
X = df.drop(['price','datesold'], axis=1).values
y = df['price'].values

In [12]:
X

array([[2607, 'house', 4],
       [2906, 'house', 3],
       [2905, 'house', 3],
       ...,
       [2912, 'unit', 2],
       [2601, 'unit', 2],
       [2612, 'unit', 2]], dtype=object)

In [15]:
y

array([525000, 290000, 328000, ..., 464950, 589000, 775000], dtype=int64)

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [17]:
X

array([[1.0, 0.0, 2607, 4],
       [1.0, 0.0, 2906, 3],
       [1.0, 0.0, 2905, 3],
       ...,
       [0.0, 1.0, 2912, 2],
       [0.0, 1.0, 2601, 2],
       [0.0, 1.0, 2612, 2]], dtype=object)

In [18]:
# Train Test Split
# Write your code here

In [19]:
# Feature Scaling
# Write your code here

In [1]:
# Model Building
# Write your code here

In [21]:
# Predicting the test results
# Write your code here

#### Out of the sample prediction

In [8]:
df.head(1)

datesold  postcode   price propertyType  bedrooms
0  2007-02-07 00:00:00      2607  525000        house         4

In [26]:
X

array([[1.0, 0.0, 2607, 4],
       [1.0, 0.0, 2906, 3],
       [1.0, 0.0, 2905, 3],
       ...,
       [0.0, 1.0, 2912, 2],
       [0.0, 1.0, 2601, 2],
       [0.0, 1.0, 2612, 2]], dtype=object)

In [15]:


data = [[0.0, 1.0, 2612, 2]]

# Create pandas dataframe
new_df = pd.DataFrame(data)

In [29]:
new_df = sc.transform(new_df)

In [14]:
single = model.predict(new_df)

print(single)

NameError: name 'model' is not defined